name: Bump
main: io.github.slimefunguguproject.bump.implementation.Bump
website: https://github.com/SlimefunGuguProject/Bump
version: '${project.version}'
api-version: 1.14
authors:
  - bxx2004
  - Lobbytech-MC
  - zimzaza4
  - haiman233
  - ybw0014
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
